bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = "news"
urlpatterns = [
    url(r"^$", views.NewsListView.as_view(), name="list"),
    # url(
    #     r"^delete/(?P<pk>[-\w]+)/$", views.NewsDeleteView.as_view(), name="delete_news"
    # ),
    url(r"^remove/$", views.remove_news, name="remove_news"),
    url(r"^post-news/$", views.post_news, name="post_news"),
    url(r"^like/$", views.like, name="like_post"),
    url(r"^get-thread/$", views.get_thread, name="get_thread"),
    url(r"^post-comment/$", views.post_comment, name="post_comments"),
    url(
        r"^update-interactions/$", views.update_interactions, name="update_interactions"
    ),
    url(r'^(?P<pk>[\w.@+-]+)/$', views.news, name='news'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = "qa"
urlpatterns = [
    url(r"^$", views.QuestionListView.as_view(), name="index_noans"),
    url(r"^answered/$", views.QuestionAnsListView.as_view(), name="index_ans"),
    url(r"^indexed/$", views.QuestionsIndexListView.as_view(), name="index_all"),
    url(
        r"^question-detail/(?P<pk>\d+)/$",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    url(r"^ask-question/$", views.CreateQuestionView.as_view(), name="ask_question"),
    url(
        r"^propose-answer/(?P<question_id>\d+)/$",
        views.CreateAnswerView.as_view(),
        name="propose_answer",
    ),
    url(r"^question/vote/$", views.question_vote, name="question_vote"),
    url(r"^answer/vote/$", views.answer_vote, name="answer_vote"),
    url(r"^accept-answer/$", views.accept_answer, name="accept_answer"),
    url(
        r"^tag/(?P<tag>[-\w]+)/$",
        views.QuestionListView.as_view(),
        name="index_noans_tagged",
    ),
    url(
        r"^answered/tag/(?P<tag>[-\w]+)/$",
        views.QuestionAnsListView.as_view(),
        name="index_ans_tagged",
    ),
    url(
        r"^indexed/tag/(?P<tag>[-\w]+)/$",
        views.QuestionsIndexListView.as_view(),
        name="index_all_tagged",
    ),
]

bootcamp/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
    path('signup/',views.UserCreateView.as_view(), name="signup"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    url(
        r"^about/$",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^accounts/", include("allauth.urls")),
    # Third party apps here
    url(r"^comments/", include("django_comments.urls")),
    url(r"^graphql", GraphQLView.as_view(graphiql=True)),
    url(r"^markdownx/", include("markdownx.urls")),
    # Local apps here
    url(
        r"^notifications/",
        include("bootcamp.notifications.urls", namespace="notifications"),
    ),
    url(r"^articles/", include("bootcamp.articles.urls", namespace="articles")),
    url(r"^news/", include("bootcamp.news.urls", namespace="news")),
    url(r"^messages/", include("bootcamp.messager.urls", namespace="messager")),
    url(r"^qa/", include("bootcamp.qa.urls", namespace="qa")),
    url(r"^search/", include("bootcamp.search.urls", namespace="search")),
    url("", include("bootcamp.users.urls", namespace="users")),
    url(r"^groups/", include("bootcamp.groups.urls", namespace="groups")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns


# flatpages urls
# urlpatterns.append(url(r'^', include('django.contrib.flatpages.urls')))

bootcamp/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from bootcamp.articles.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(
        widget=forms.HiddenInput(), required=False, initial=False
    )
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ["title", "content", "image", "tags", "status", "edited"]

bootcamp/groups/forms.py
from django import forms

from .models import Group


class GroupForm(forms.ModelForm):
    """
    Form that handles group data.
    """
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))
    cover = forms.ImageField(
        widget=forms.FileInput(),
        help_text="Image dimensions should be <b>900 &#10005; 300</b>.",
        required=False
    )

    class Meta:
        model = Group
        fields = ('title', 'description', 'cover')

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article, TaggedArticle
from bootcamp.articles.forms import ArticleForm

from taggit.views import TagListMixin


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""

    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["popular_tags"] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class ArticlesByTagListView(TagListMixin, ArticlesListView):
    template_name = 'articles/article_list.html'

    def get_queryset(self, **kwargs):
        qs = Article.objects.filter(
            pk__in=TaggedArticle.objects.filter(tag=self.tag).values_list("content_object_id", flat=True))
        return qs.get_published()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["filtered_by_tag"] = self.tag
        return context


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""

    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""

    model = Article
    message = _("Your article has been created.")
    form_class = ArticleForm
    template_name = "articles/article_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("articles:list")


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""

    model = Article
    message = _("Your article has been updated.")
    form_class = ArticleForm
    template_name = "articles/article_update.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("articles:list")


class DetailArticleView(LoginRequiredMixin, DetailView):
    """Basic DetailView implementation to call an individual article."""

    model = Article

bootcamp/groups/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

import requests
from PIL import Image

from .decorators import user_is_not_banned_from_group, user_is_group_admin
from .forms import GroupForm
from .models import Group
from ..helpers import ajax_required
from ..news.models import News
from ..utils import check_image_extension


class GroupsPageView(ListView):
    """
    Basic ListView implementation to call the groups list.
    """
    model = Group
    queryset = Group.objects.all()
    paginate_by = 20
    template_name = 'groups/view_all_groups.html'
    context_object_name = 'groups'


class GroupPageView(ListView):
    """
    Basic ListView implementation to call the news list per group.
    """
    model = News
    paginate_by = 20
    template_name = 'groups/group.html'
    context_object_name = 'news'

    def get_queryset(self, **kwargs):
        self.group = get_object_or_404(Group,
                                       slug=self.kwargs['group'])
        return self.group.submitted_news.all()
        # return self.group.submitted_news.filter(active=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["bv"] = True
        context["admins"] = self.group.admins.all()
        context["group"] = self.group
        return context


class UserSubscriptionListView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the subscriptions list per user.
    """
    model = Group
    paginate_by = 10
    template_name = 'groups/user_subscription_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.subscribed_groups.all()


@login_required
@ajax_required
@user_is_not_banned_from_group
def subscribe(request, group):
    """
    Subscribes a group & returns subscribers count.
    """
    group = get_object_or_404(Group,
                              slug=group)
    user = request.user
    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
    else:
        group.subscribers.add(user)
    return HttpResponse(group.subscribers.count())


class UserCreatedGroupsPageView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the groups list per user.
    """
    model = Group
    paginate_by = 20
    template_name = 'groups/user_created_groups.html'
    context_object_name = 'user_groups'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.inspected_groups.all()


@login_required
def new_group(request):
    """
    Displays a form & handle action for creating new group.
    """
    group_form = GroupForm()

    if request.method == 'POST':
        group_form = GroupForm(request.POST, request.FILES)
        if group_form.is_valid():
            new_group = group_form.save()
            new_group.admins.add(request.user)
            new_group.subscribers.add(request.user)
            return redirect(new_group.get_absolute_url())
            
    form_filling = True

    return render(request, 'groups/new_group.html', {
        'group_form': group_form, 'form_filling': form_filling
    })


@login_required
@user_is_group_admin
def edit_group_cover(request, group):
    """
    Displays edit form for group cover and handles edit action.
    """
    group = get_object_or_404(Group,
                              slug=group)
    if request.method == 'POST':
        group_cover = request.FILES.get('cover')
        if check_image_extension(group_cover.name):
            group.cover = group_cover
            group.save()
            return redirect('group', group=group.slug)
        else:
            return HttpResponse('Filetype not supported. Supported filetypes are .jpg, .png etc.')
    else:
        form_filling = True
        return render(request, 'groups/edit_group_cover.html', {
            'group': group, 'form_filling': form_filling
        })


@login_required
@user_is_group_admin
def banned_users(request, group):
    """
    Displays a list of banned users to the group admins.
    """
    group = get_object_or_404(Group,
                              slug=group)
    users = group.banned_users.all()

    paginator = Paginator(users, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True
    else:
        p = False
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    p_obj = users
    bv = True

    return render(request, 'groups/banned_users.html', {
        'group': group,
        'bv': bv,
        'page': page,
        'p_obj': p_obj,
        'p': p,
        'users': users
    })


@login_required
@user_is_group_admin
def ban_user(request, group, user_id):
    """
    Handles requests from group admins to ban users from the group.
    """
    group = get_object_or_404(Group,
                              slug=group)
    user = get_object_or_404(User,
                             id=user_id)
    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
        group.banned_users.add(user)
        return redirect('banned_users', group=group.slug)
    else:
        group.banned_users.remove(user)
        return redirect('banned_users', group=group.slug)

bootcamp/notifications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.http import (
    JsonResponse,
    HttpResponseForbidden,
    HttpResponse,
    HttpResponseBadRequest,
)

from bootcamp.helpers import ajax_required
from bootcamp.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to show the unread notifications for
    the actual user"""

    model = Notification
    context_object_name = "notification_list"
    template_name = "notifications/notification_list.html"

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.all()


@login_required
def mark_all_as_read(request):
    """View to call the model method which marks as read all the notifications
    directed to the actual user."""
    request.user.notifications.mark_all_as_read()
    _next = request.GET.get("next")
    messages.add_message(
        request,
        messages.SUCCESS,
        _(f"All notifications to {request.user.username} have been marked as read."),
    )

    if _next:
        return redirect(_next)

    return redirect("notifications:unread")


@login_required
def mark_as_read(request, slug=None):
    """View to call the model method which mark as read the provided
    notification."""
    if slug:
        notification = get_object_or_404(Notification, slug=slug)
        notification.mark_as_read()

    messages.add_message(
        request,
        messages.SUCCESS,
        _(f"The notification {notification.slug} was marked as read."),
    )
    _next = request.GET.get("next")

    if _next:
        return redirect(_next)

    return redirect("notifications:unread")


@login_required
@ajax_required
@require_http_methods(["POST"])
def mark_as_read_ajax(request):
    try:
        slug = request.POST["slug"]
        if slug:
            notification = get_object_or_404(Notification, slug=slug)
            notification.mark_as_read()

        return HttpResponse()

    except Exception:
        return HttpResponseBadRequest()


@login_required
def get_latest_notifications(request):
    notifications = request.user.notifications.get_most_recent()
    request.user.notifications.mark_all_as_read()
    return render(
        request, "notifications/most_recent.html", {"notifications": notifications}
    )


@login_required
def get_unread_notifications(request):
    notifications = request.user.notifications.unread()
    return JsonResponse({"unread_notifications": str(len(notifications))})

bootcamp/templates/qa/answer_form.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Answer a question' %}{% endblock %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'qa:index_all' %}">{% trans 'Q&A' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Answer a question' %}</li>
    </ol>
  </nav>
  <form action="{% url 'qa:propose_answer' view.kwargs.question_id %}" id="answerForm" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button id="answer" type="submit" class="btn btn-primary">{% trans 'Answer' %}</button>
      <a href="{% url 'qa:index_all' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

bootcamp/templates/qa/question_detail.html
{% extends 'base.html' %}
{% load i18n static humanize %}

{% block title %}{{ question.title }}{% endblock %}

{% block head %}
  <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'qa:index_noans' %}">{% trans 'Q.A' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ question.title }}</li>
      </ol>
    </nav>
    <div class="page-header">
      <a href="{% url 'qa:ask_question' %}" class="btn btn-primary pull-right">
        <i class="fa fa-pencil" aria-hidden="true"></i> {% trans "Ask a Question" %}
      </a>
      <h1>{{ question.title }}</h1>
    </div>
    <div class="row question" question-id="{{ question.id }}">
      <div class="col-md-1">
        <div class="question-info options">
          <h3 class="{% if question.has_answer %}bg-success text-white{% endif %}">{{ question.count_answers }}</h3>
          <small class="text-secondary">{% trans 'Answers' %}</small>
          <i id="questionUpVote" class="fa fa-chevron-up {% if is_question_owner %} is-owner {% else %} vote {% endif %} up-vote question-vote{% if request.user in question.get_upvoters %} voted{% endif %}" aria-hidden="true" title="{% trans 'Click to up vote; click again to toggle' %}"></i>
          <h3 id="questionVotes">{{ question.total_votes }}</h3>
          <i id="questionDownVote" class="fa fa-chevron-down {% if is_question_owner %} is-owner {% else %} vote {% endif %} down-vote question-vote{% if request.user in question.get_downvoters %} voted{% endif %}" aria-hidden="true" title="{% trans 'Click to down vote; click again to toggle' %}"></i>
          <small class="text-secondary">{% trans 'Votes' %}</small>
        </div>
      </div>
      <div class="col-md-11">
        <p>{{ question.get_markdown|safe }}</p>
        <div class="question-user pull-right">
          <span class="text-secondary">{% trans 'Asked' %} {{ question.timestamp|naturaltime }} {% trans 'by' %}</span>
          <a href="{% url 'users:detail' question.user.username  %}">{{ question.user.get_profile_name|title }}</a>
          {% if question.tags.names %}
            <p>
              {% for tag in question.tags.all %}
                <a href="{% url 'qa:index_noans' %}tag/{{ tag.slug }}"><span class="badge badge-primary">{{ tag.name }}</span></a>
              {% endfor %}
            </p>
          {% endif %}
        </div>
      </div>
        <a href="{% url 'qa:propose_answer' question.id %}" class="btn btn-primary pull-right" role="button">{% trans "Submit an answer" %}</a>
    </div>
    <div class="page-header">
      <h1>{% trans 'Answers' %}</h1>
    </div>
    <div class="row">
      <ul class="col-md-12">
        {% for answer in question.answer_set.all %}
          {% include 'qa/answer_sample.html' with answer=answer username=request.user.username %}
        {% empty %}
          <div class="text-center">
            <h4>{% trans 'There are no answers yet.' %}</h4>
            <p>{% trans 'Submit your answer now.' %}</p>
          </div>
        {% endfor %}
      </ul>
    </div>
{% endblock content %}


{% block modal %}
  <script src="{% static 'js/qa.js' %}" type="text/javascript"></script>
{% endblock modal %}

bootcamp/templates/qa/question_form.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Ask a question' %}{% endblock %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'qa:index_all' %}">{% trans 'Q&A' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Ask a question' %}</li>
    </ol>
  </nav>
  <form action="{% url 'qa:ask_question' %}" enctype="multipart/form-data"  id="question-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button id="publish" type="button" class="btn btn-primary">{% trans 'Publish' %}</button>
      <button id="draft" type="button" class="btn btn-default">{% trans 'Save as draft' %}</button>
      <a href="{% url 'qa:index_all' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/qa.js' %}"></script>
{% endblock modal %}

bootcamp/templates/qa/question_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans "Questions" %}{% endblock %}

{% block head %}
  <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li>
      {% if view.kwargs.tag %}
        <li class="breadcrumb-item"><a href="{{ qa_url }}">{% trans 'Q.A' %}</a></li>
        <li class="breadcrumb-item active"><a href="{{ qa_url }}tag/{{ view.kwargs.tag }}">{{ view.kwargs.tag }}</a></li>
      {% else %}
        <li class="breadcrumb-item active"><a href="{{ qa_url }}">{% trans 'Q.A' %}</a></li>
      {% endif %}
    </ol>
  </nav>
  <div class="page-header">
    <a href="{% url 'qa:ask_question' %}" class="btn btn-primary pull-right">
      <i class="fa fa-pencil" aria-hidden="true"></i> {% trans "Ask a Question" %}
    </a>
    <h1>{% trans "Questions" %}</h1>
  </div>
  <div class="card my-4">
    <h5 class="card-header">{% trans 'Questions by topic' %}</h5>
    <div class="card-body">
      {% for tag, tag_props in popular_tags %}
        {% if tag_props.slug == view.kwargs.tag %}
          <a href="{{ qa_url }}">
            <span class="badge badge-success">{{ tag_props.count }} {{ tag }} <i class="fa fa-times" aria-hidden="true"></i></span>
          </a>
        {% else %}
          <a href="{{ qa_url }}tag/{{ tag_props.slug }}">
            <span class="badge badge-info">{{ tag_props.count }} {{ tag }}</span>
          </a>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  <div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link{% if active == 'unanswered' %} active{% endif %}" href="{% url 'qa:index_noans' %}{% if view.kwargs.tag %}tag/{{ view.kwargs.tag }}{% endif %}">
          {% trans "Unanswered" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'answered' %} active{% endif %}" href="{% url 'qa:index_ans' %}{% if view.kwargs.tag %}tag/{{ view.kwargs.tag }}{% endif %}">
          {% trans "Answered" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'all' %} active{% endif %}" href="{% url 'qa:index_all' %}{% if view.kwargs.tag %}tag/{{ view.kwargs.tag }}{% endif %}">
          {% trans "All Questions" %}
        </a>
      </li>
    </ul>
    {% for question in questions %}
      {% include 'qa/question_sample.html' with question=question %}
    {% empty %}
      <h4 class="no-data">{% trans "No question to display" %}</h4>
    {% endfor %}

    {% if is_paginated %}
      <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Newer' %}</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Older' %} &rarr;</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock content %}


{% block modal %}
  <script src="{% static 'js/qa.js' %}"></script>
{% endblock modal %}

bootcamp/templates/qa/question_sample.html
{% load humanize i18n static humanize %}
{% load thumbnail %}

<div class="card questions">
  <div class="card-body">
    <div class="question-info pull-left text-center">
      <h3 class="{% if question.has_answer %}bg-success text-white{% endif %}">{{ question.count_answers }}</h3>
      <small class="text-secondary">{% trans 'Answers' %}</small>
      <h3>{{ question.total_votes }}</h3>
      <small class="text-secondary">{% trans 'Votes' %}</small>
    </div>
    <div>
      <h4 class="card-title">
        <a href="{% url 'qa:question_detail' question.pk %}">{{ question.title }}</a>
      </h4>
      <p>{{ question.get_markdown|safe|truncatechars:100 }}</p>
      <div class="question-user pull-right">
        <span class="text-secondary">{% trans 'Asked' %} {{ question.timestamp|naturaltime }} {% trans 'by' %}</span>
        <a href="{% url 'users:detail' question.user.username  %}">{{ question.user.get_profile_name|title }}</a>
        {% if question.tags.names %}
          <p style="position: absolute; bottom: 0;">
            {% for tag in question.tags.all %}
              <a href="{% if qa_url %}{{ qa_url }}{% else %}{% url 'qa:index_noans' %}{% endif %}tag/{{ tag.slug }}"><span class="badge badge-primary">{{ tag.name }}</span></a>
            {% endfor %}
          </p>
        {% endif %}
      </div>
    </div>
  </div>
</div>