bootcamp/messager/urls.py
from django.conf.urls import url

from bootcamp.messager import views

app_name = "messager"
urlpatterns = [
    url(r"^$", views.MessagesListView.as_view(), name="messages_list"),
    url(r"^send-message/$", views.send_message, name="send_message"),
    url(r"^receive-message/$", views.receive_message, name="receive_message"),
    url(r"^mark-read-messages/$", views.mark_read_messages, name="mark_read_messages"),
    url(
        r"^get-unread-messages/$",
        views.get_unread_messages,
        name="get_unread_messages",
    ),
    url(
        r"^(?P<username>[\w.@+-]+)/$",
        views.ConversationListView.as_view(),
        name="conversation_detail",
    ),
]

bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = "news"
urlpatterns = [
    url(r"^$", views.NewsListView.as_view(), name="list"),
    # url(
    #     r"^delete/(?P<pk>[-\w]+)/$", views.NewsDeleteView.as_view(), name="delete_news"
    # ),
    url(r"^remove/$", views.remove_news, name="remove_news"),
    url(r"^post-news/$", views.post_news, name="post_news"),
    url(r"^like/$", views.like, name="like_post"),
    url(r"^get-thread/$", views.get_thread, name="get_thread"),
    url(r"^post-comment/$", views.post_comment, name="post_comments"),
    url(
        r"^update-interactions/$", views.update_interactions, name="update_interactions"
    ),
    url(r'^(?P<pk>[\w.@+-]+)/$', views.news, name='news'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = "qa"
urlpatterns = [
    url(r"^$", views.QuestionListView.as_view(), name="index_noans"),
    url(r"^answered/$", views.QuestionAnsListView.as_view(), name="index_ans"),
    url(r"^indexed/$", views.QuestionsIndexListView.as_view(), name="index_all"),
    url(
        r"^question-detail/(?P<pk>\d+)/$",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    url(r"^ask-question/$", views.CreateQuestionView.as_view(), name="ask_question"),
    url(
        r"^propose-answer/(?P<question_id>\d+)/$",
        views.CreateAnswerView.as_view(),
        name="propose_answer",
    ),
    url(r"^question/vote/$", views.question_vote, name="question_vote"),
    url(r"^answer/vote/$", views.answer_vote, name="answer_vote"),
    url(r"^accept-answer/$", views.accept_answer, name="accept_answer"),
    url(
        r"^tag/(?P<tag>[-\w]+)/$",
        views.QuestionListView.as_view(),
        name="index_noans_tagged",
    ),
    url(
        r"^answered/tag/(?P<tag>[-\w]+)/$",
        views.QuestionAnsListView.as_view(),
        name="index_ans_tagged",
    ),
    url(
        r"^indexed/tag/(?P<tag>[-\w]+)/$",
        views.QuestionsIndexListView.as_view(),
        name="index_all_tagged",
    ),
]

bootcamp/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
    path('signup/',views.UserCreateView.as_view(), name="signup"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    url(
        r"^about/$",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^accounts/", include("allauth.urls")),
    # Third party apps here
    url(r"^comments/", include("django_comments.urls")),
    url(r"^graphql", GraphQLView.as_view(graphiql=True)),
    url(r"^markdownx/", include("markdownx.urls")),
    # Local apps here
    url(
        r"^notifications/",
        include("bootcamp.notifications.urls", namespace="notifications"),
    ),
    url(r"^articles/", include("bootcamp.articles.urls", namespace="articles")),
    url(r"^news/", include("bootcamp.news.urls", namespace="news")),
    url(r"^messages/", include("bootcamp.messager.urls", namespace="messager")),
    url(r"^qa/", include("bootcamp.qa.urls", namespace="qa")),
    url(r"^search/", include("bootcamp.search.urls", namespace="search")),
    url("", include("bootcamp.users.urls", namespace="users")),
    url(r"^groups/", include("bootcamp.groups.urls", namespace="groups")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns


# flatpages urls
# urlpatterns.append(url(r'^', include('django.contrib.flatpages.urls')))

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article, TaggedArticle
from bootcamp.articles.forms import ArticleForm

from taggit.views import TagListMixin


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""

    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["popular_tags"] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class ArticlesByTagListView(TagListMixin, ArticlesListView):
    template_name = 'articles/article_list.html'

    def get_queryset(self, **kwargs):
        qs = Article.objects.filter(
            pk__in=TaggedArticle.objects.filter(tag=self.tag).values_list("content_object_id", flat=True))
        return qs.get_published()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["filtered_by_tag"] = self.tag
        return context


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""

    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""

    model = Article
    message = _("Your article has been created.")
    form_class = ArticleForm
    template_name = "articles/article_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("articles:list")


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""

    model = Article
    message = _("Your article has been updated.")
    form_class = ArticleForm
    template_name = "articles/article_update.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("articles:list")


class DetailArticleView(LoginRequiredMixin, DetailView):
    """Basic DetailView implementation to call an individual article."""

    model = Article

bootcamp/groups/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

import requests
from PIL import Image

from .decorators import user_is_not_banned_from_group, user_is_group_admin
from .forms import GroupForm
from .models import Group
from ..helpers import ajax_required
from ..news.models import News
from ..utils import check_image_extension


class GroupsPageView(ListView):
    """
    Basic ListView implementation to call the groups list.
    """
    model = Group
    queryset = Group.objects.all()
    paginate_by = 20
    template_name = 'groups/view_all_groups.html'
    context_object_name = 'groups'


class GroupPageView(ListView):
    """
    Basic ListView implementation to call the news list per group.
    """
    model = News
    paginate_by = 20
    template_name = 'groups/group.html'
    context_object_name = 'news'

    def get_queryset(self, **kwargs):
        self.group = get_object_or_404(Group,
                                       slug=self.kwargs['group'])
        return self.group.submitted_news.all()
        # return self.group.submitted_news.filter(active=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["bv"] = True
        context["admins"] = self.group.admins.all()
        context["group"] = self.group
        return context


class UserSubscriptionListView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the subscriptions list per user.
    """
    model = Group
    paginate_by = 10
    template_name = 'groups/user_subscription_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.subscribed_groups.all()


@login_required
@ajax_required
@user_is_not_banned_from_group
def subscribe(request, group):
    """
    Subscribes a group & returns subscribers count.
    """
    group = get_object_or_404(Group,
                              slug=group)
    user = request.user
    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
    else:
        group.subscribers.add(user)
    return HttpResponse(group.subscribers.count())


class UserCreatedGroupsPageView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the groups list per user.
    """
    model = Group
    paginate_by = 20
    template_name = 'groups/user_created_groups.html'
    context_object_name = 'user_groups'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.inspected_groups.all()


@login_required
def new_group(request):
    """
    Displays a form & handle action for creating new group.
    """
    group_form = GroupForm()

    if request.method == 'POST':
        group_form = GroupForm(request.POST, request.FILES)
        if group_form.is_valid():
            new_group = group_form.save()
            new_group.admins.add(request.user)
            new_group.subscribers.add(request.user)
            return redirect(new_group.get_absolute_url())
            
    form_filling = True

    return render(request, 'groups/new_group.html', {
        'group_form': group_form, 'form_filling': form_filling
    })


@login_required
@user_is_group_admin
def edit_group_cover(request, group):
    """
    Displays edit form for group cover and handles edit action.
    """
    group = get_object_or_404(Group,
                              slug=group)
    if request.method == 'POST':
        group_cover = request.FILES.get('cover')
        if check_image_extension(group_cover.name):
            group.cover = group_cover
            group.save()
            return redirect('group', group=group.slug)
        else:
            return HttpResponse('Filetype not supported. Supported filetypes are .jpg, .png etc.')
    else:
        form_filling = True
        return render(request, 'groups/edit_group_cover.html', {
            'group': group, 'form_filling': form_filling
        })


@login_required
@user_is_group_admin
def banned_users(request, group):
    """
    Displays a list of banned users to the group admins.
    """
    group = get_object_or_404(Group,
                              slug=group)
    users = group.banned_users.all()

    paginator = Paginator(users, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True
    else:
        p = False
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    p_obj = users
    bv = True

    return render(request, 'groups/banned_users.html', {
        'group': group,
        'bv': bv,
        'page': page,
        'p_obj': p_obj,
        'p': p,
        'users': users
    })


@login_required
@user_is_group_admin
def ban_user(request, group, user_id):
    """
    Handles requests from group admins to ban users from the group.
    """
    group = get_object_or_404(Group,
                              slug=group)
    user = get_object_or_404(User,
                             id=user_id)
    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
        group.banned_users.add(user)
        return redirect('banned_users', group=group.slug)
    else:
        group.banned_users.remove(user)
        return redirect('banned_users', group=group.slug)

bootcamp/notifications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.http import (
    JsonResponse,
    HttpResponseForbidden,
    HttpResponse,
    HttpResponseBadRequest,
)

from bootcamp.helpers import ajax_required
from bootcamp.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to show the unread notifications for
    the actual user"""

    model = Notification
    context_object_name = "notification_list"
    template_name = "notifications/notification_list.html"

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.all()


@login_required
def mark_all_as_read(request):
    """View to call the model method which marks as read all the notifications
    directed to the actual user."""
    request.user.notifications.mark_all_as_read()
    _next = request.GET.get("next")
    messages.add_message(
        request,
        messages.SUCCESS,
        _(f"All notifications to {request.user.username} have been marked as read."),
    )

    if _next:
        return redirect(_next)

    return redirect("notifications:unread")


@login_required
def mark_as_read(request, slug=None):
    """View to call the model method which mark as read the provided
    notification."""
    if slug:
        notification = get_object_or_404(Notification, slug=slug)
        notification.mark_as_read()

    messages.add_message(
        request,
        messages.SUCCESS,
        _(f"The notification {notification.slug} was marked as read."),
    )
    _next = request.GET.get("next")

    if _next:
        return redirect(_next)

    return redirect("notifications:unread")


@login_required
@ajax_required
@require_http_methods(["POST"])
def mark_as_read_ajax(request):
    try:
        slug = request.POST["slug"]
        if slug:
            notification = get_object_or_404(Notification, slug=slug)
            notification.mark_as_read()

        return HttpResponse()

    except Exception:
        return HttpResponseBadRequest()


@login_required
def get_latest_notifications(request):
    notifications = request.user.notifications.get_most_recent()
    request.user.notifications.mark_all_as_read()
    return render(
        request, "notifications/most_recent.html", {"notifications": notifications}
    )


@login_required
def get_unread_notifications(request):
    notifications = request.user.notifications.unread()
    return JsonResponse({"unread_notifications": str(len(notifications))})

bootcamp/templates/users/user_account_menu.html
{% load i18n %}

<div class="list-group">
    <a href="{% url 'users:update' %}"
       class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
    <a href="{% url 'users:picture' %}"
       class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
    <a href="{% url 'users:account_change_password' %}"
       class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>

bootcamp/templates/users/user_account_partial_menu.html
{% load i18n %}

<div class="list-group">
    <a href="{% url 'users:update' %}"
       class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
    <a href="{% url 'users:picture' %}"
       class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
    <a href="{% url 'users:account_change_password' %}"
       class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>

bootcamp/templates/users/user_detail.html
{% extends "base.html" %}
{% load static humanize i18n %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block head %}
    <link href="{% static 'css/user_profile.css' %}?v=1" rel="stylesheet">
    <link href="{% static 'css/news.css' %}?v=1" rel="stylesheet">

{% endblock head %}

{% block content %}
    {#    {% if request.user.username == object.username %}#}
    {#    {% endif %}#}
    <div class="page-header">
        <h1>{% trans 'Profile' %}</h1>
    </div>
    <div class="row">
        <div class="col-md-3 user-profile" style="text-align:center">
            <img src="{{ object.get_picture }}" class="user-image"
                 style="width: 150px; border-radius: 50%;"
                 alt="{% trans 'User Image' %}">
            {#            {% include 'users/user_profile_menu.html' with active='user_detail' %}#}

        </div>
        <div class="col-md-8">
            <div id="contact-info" class="card" style="margin-bottom: 15px">
                <div class="card-body">
                    <h4 class="card-title">
                        {% ifequal request.user object %}
                        {% else %}
                            {% if not request.user in object.contact_list.all %}
                                {% if request.user in object.pending_list.all %}
                                    <a href="{% url 'users:send_message_request' object.id %}"
                                       class="btn btn-primary btn-sm"
                                       id="send_message_request"
                                       style="margin-right: 10px;"
                                       title="Request sent to this users">Request Sent</a>
                                {% else %}
                                    <a href="{% url 'users:send_message_request' object.id %}"
                                       class="btn btn-outline-primary btn-sm"
                                       id="send_message_request"
                                       style="margin-right: 10px;"
                                       title="Send request to this user to start conversation">Send Request</a>
                                {% endif %}
                            {% else %}
                                <!-- Block User Trigger -->
                                <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal"
                                        data-target="#blockUserModel">Block
                                </button>

                                <!-- Block User Modal -->
                                <div class="modal fade" id="blockUserModel" tabindex="-1" role="dialog"
                                     aria-labelledby="Block User" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Are you sure?</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <h5>Once you block the user, you cannot message him again until he
                                                    accepts your
                                                    request.</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary btn-sm"
                                                        data-dismiss="modal">
                                                    Cancel
                                                </button>
                                                <a href="{% url 'users:block_spammer' object.id %}"
                                                   class="btn btn-primary btn-sm"
                                                   id="block_spammer" style="margin-right: 10px;"
                                                   title="Block this user">Block</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'messager:conversation_detail' object.username %}"
                                   class="btn btn-outline-primary btn-sm"
                                   id="send_msg" title="Send message to this user"
                                   style="margin-right: 10px;">Message</a>
                            {% endif %}
                        {% endifequal %}

                        {% ifequal request.user object %}
                        {% else %}
                            {% if request.user in object.followers.all %}
                                <a href="{% url 'users:follow_user' object.id %}" class="btn btn-primary btn-sm"
                                   id="follow_user">Unfollow</a>
                            {% else %}
                                <a href="{% url 'users:follow_user' object.id %}"
                                   class="btn btn-outline-primary btn-sm"
                                   id="follow_user">Follow</a>
                            {% endif %}
                        {% endifequal %}
                    </h4>
                    <h1 class="fn">
                        {{ object.get_profile_name }}
                        {% ifequal request.user object %}
                            <a href="{% url 'users:update' %}"
                               class="btn btn-primary pull-right">{% trans 'Edit Profile' %}</a>
                        {% endifequal %}
                    </h1>
                    <p>
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        {{ object.username }}
                        <br/>
                        {% if object.job_title %}
                            <i class="fa fa-briefcase" aria-hidden="true"></i> {{ object.job_title }} <br/>
                        {% endif %}
                        {% if object.location %}
                            <i class="fa fa-map-marker" aria-hidden="true"></i> {{ object.location }} <br/>
                        {% endif %}
                        <i class="fa fa-clock-o"></i>{% trans ' Last Login: ' %} <small
                            class="timestamp">{{ object.last_login|naturaltime }}</small>
                        <br/>
                     <i class="fa fa-calendar"></i>{% trans ' Member Since: ' %} <small
                            class="timestamp">{{ object.member_since|naturaltime }}</small>
                    </p>
                    <div id="objective"><p>{{ object.bio }}</p></div>
                    <div class="clear"></div>
                    {% if object.personal_url %}
                        <a href="{{ object.personal_url }}" style="font-size: 2em" title="{% trans 'RSS Channel' %}"><i
                                class="fa fa-rss"></i> </a>
                    {% endif %}
                </div>
            </div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#user_activity">Activity</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#user_friends">Friends</a>
                </li>
                {% ifequal request.user object %}
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#user_friend_requests">Friend Requests</a>
                    </li>
                {% endifequal %}
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#user_followers">Followers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#user_following">Following</a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div id="user_activity" class="tab-pane active"><br>
                    {% include 'users/user_activity.html' with user_activity=user_activity %}
                </div>
                {% ifequal request.user object %}
                    <div id="user_friend_requests" class="tab-pane fade"><br>
                        {% include 'users/user_friend_requests.html' with users=object.pending_list.all %}
                    </div>
                {% endifequal %}
                <div id="user_friends" class="tab-pane fade"><br>
                    {% include 'users/user_friends.html' with users=object.contact_list.all %}
                </div>
                <div id="user_followers" class="tab-pane fade"><br>
                    {% include 'users/user_followers.html' with users=object.followers.all %}
                </div>
                <div id="user_following" class="tab-pane fade"><br>
                    {% include 'users/user_following.html' %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block modal %}
    {% include "users/includes/partial_user_js.html" %}
    <script src="{% static 'js/jquery.waypoints.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/infinite.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/news.js' %}" type="text/javascript"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.load').show();
            },
            onAfterPageLoad: function ($items) {
                $('.load').hide();
            }
        });
    </script>
{% endblock modal %}

bootcamp/templates/users/user_following.html
{% load static i18n %}
{% load humanize %}

{% block head %}
    <link href="{% static 'css/user_profile.css' %}?v=1" rel="stylesheet">
{% endblock head %}

{% block content %}
    {#    <!--    {% if request.user.username == object.username %}-->#}
    {#        <!--    {% endif %}-->#}
    {% for user in users %}
        <div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
            <div class="card-body p-4">

                <div class="text-center" style="float:left; width:10%;">
                    {% if user.get_picture %}
                        <img src="{{ user.get_picture }}" class="rounded" width="50px" height="50px">
                    {% endif %}
                </div>

                <div style="float:right; width:90%;">
                    <h5 style="font-size:16px;">
                        <a href="{% url 'users:detail' user.username %}"
                           class="card-link"
                           title="{{ user.username }}">{{ username }}</a>
                    </h5>
                    {#                            <p class="text-muted">Member since <span#}
                    {#                                title="{{ profile.member_since|date:" D d M Y" }} |#}
                    {#                        {{ profile.member_since|time:"H:i:s" }}">{{ profile.member_since|naturaltime }}</span></p>#}
                </div>
            </div>
        </div>
    {% empty %}
        <div class="card p-4 my-4 mx-0">
            <h6 class="text-center">No Following Found</h6>
            <div style="margin:0 auto;">
                <p class="text-muted">You don't have any following right now.</p>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

bootcamp/templates/users/user_partial_menu.html
{% load i18n %}

{#<img src="{{ user.get_picture }}" class="user-image"#}
{#     style="width: 150px; border-radius: 50%; margin-bottom: 2rem; margin-left: 2rem;"#}
{#     alt="{% trans 'User Image' %}">#}

<div class="list-group">
    <a href="{% url 'users:update' %}"
       class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
    <a href="{% url 'users:picture' %}"
       class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
    <a href="{% url 'users:account_change_password' %}"
       class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>